language: python
addons:
  apt:
    update: true
sudo: false
cache: pip
git:
  depth: false

matrix:
  include:
    - python: 3.5
    - python: 3.6

script:
  - python -m coverage run -p -m unittest loggerhead.tests.test_suite

install:
  - sudo apt install subunit adduser libjs-jquery
  - travis_retry pip install -U setuptools
  - travis_retry pip install -U pip coverage codecov flake8 testtools configobj cython testscenarios six docutils python-subunit dulwich bzr+lp:brz pygments paste Chameleon bleach

after_success:
  - codecov
