.TH LOGGERHEAD "1" "August 2008" "loggerhead 1.6" "User Commands"
.SH NAME
loggerhead \- run a loggerhead server
.SH SYNOPSIS
.B loggerhead-serve
[\fIoptions\fR] \fI<path>\fR
.SH DESCRIPTION
Loggerhead is a web viewer for projects in Breezy. It can be used to navigate 
a branch history, annotate files, view patches, perform searches, etc. It's 
heavily based on bazaar-webserve, which is itself based on hgweb for Mercurial.
.PP
The loggerhead-serve command runs a standalone loggerhead server in the foreground.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-user\-dirs\fR
Serve user directories as ~user.
.TP
\fB\-\-trunk\-dir\fR=\fIDIR\fR
The directory that contains the trunk branches.
.TP
\fB\-\-port\fR
Port Loggerhead should listen on (defaults to 8080).
.TP
\fB\-\-host\fR
Host Loggerhead should listen on.
.TP
\fB\-\-prefix\fR
Specify host prefix.
.TP
\fB\-\-reload\fR
Restarts the application when changing python files. Only used for development purposes.
.TP
\fB\-\-log\-folder\fR=\fILOG_FOLDER\fR
The directory to place log files
.TP
\fB\-\-version\fR
Print the software version and exit.
.SH "LICENSE"
GNU GPLv2 or later.
.SH "SEE ALSO"
https://launchpad.net/loggerhead
