.TH STOP-LOGGERHEAD "1" "July 2008" "stop-loggerhead 1.2.1" "User Commands"
.SH NAME
stop-loggerhead \- stop a loggerhead server
.SH SYNOPSIS
.B stop-loggerhead
.SH DESCRIPTION
Loggerhead is a web viewer for projects in bazaar. It can be used to navigate 
a branch history, annotate files, view patches, perform searches, etc. It's 
heavily based on bazaar-webserve, which is itself based on hgweb for Mercurial.
.PP
The stop-loggerhead command stops the currently running loggerhead server.
.SH "LICENSE"
GNU GPLv2 or later.
.SH "SEE ALSO"
https://launchpad.net/loggerhead
